image: debian/bullseye
packages:
- rsync
- xorg-dev
- libxi-dev
- libxcursor-dev
- mingw-w64
repositories: {}
secrets:
- 09e2cbc4-14d3-473d-9855-d14a906bda1e
shell: false
tasks:
- build: |
    cd ~/tophat
    make
    make cross
- deploy: |
    cd ~/tophat
    rsync --rsh="ssh -o StrictHostKeyChecking=no" tophat marek@tophat2d.dev:www/tophat-web/dl/tophat-linux
    rsync --rsh="ssh -o StrictHostKeyChecking=no" tophat.exe marek@tophat2d.dev:www/tophat-web/dl/tophat-windows.exe
- event: |
    cd ~/tophat
    ssh -o 'StrictHostKeyChecking no' marek@tophat2d.dev /home/marek/on-tophat-push
