image: archlinux
packages:
    - rsync
    - libx11
    - libxi
    - libxcursor
    - mingw-w64-gcc
    - mesa
sources:
    - https://git.sr.ht/~mrms/tophat
secrets:
    - 09e2cbc4-14d3-473d-9855-d14a906bda1e
tasks:
    - build: |
        cd ~/tophat
        make
        make cross
    - deploy: |
        cd ~/tophat
        rsync --rsh="ssh -o StrictHostKeyChecking=no" tophat marek@mrms.cz:tophat-web/dl/tophat-linux
        rsync --rsh="ssh -o StrictHostKeyChecking=no" tophat.exe marek@mrms.cz:tophat-web/dl/tophat-window.exe
    - event: |
        cd ~/tophat
        ssh -o 'StrictHostKeyChecking no' marek@mrms.cz /home/marek/on-tophat-push

