name: Tophat auto package workflow
on: [push]
jobs:
  Linux-Package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        sudo apt-get install gcc zip make libx11-dev libgl-dev
        make deps
        make package
