name: Tophat auto package workflow
on: [push]
jobs:
  Linux-Package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        sudo apt-get install gcc zip make libx11-dev
        git submodule update --recursive --remote
        make deps
        make package
