name: Tophat workflow
on: [push]
jobs:
  MakePkg-Msbuild:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build with CMake+MSbuild
      run: |
        git submodule init
        git submodule update --remote
        ./msbuild.bat
